name: Deploy Project

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Upload files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "docker-compose.yml,minio-setup.sh,nginx.conf"
        target: "${{ vars.DIR }}"

    - name: Copy .env.sample to .env
      run: cp .env.sample .env
  
    - name: Upload .env
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        source: ".env"
        target: "${{ vars.DIR }}"
            
    - name: Run docker compose
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ${{ vars.DIR }}
          docker compose pull
          docker compose down
          docker compose up -d
  
    - name: Check containers health
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ${{ vars.DIR }}
           docker compose ps
           timeout=60
           echo "⌛ Waiting for containers to become healthy..."
          while [[ $timeout -gt 0 ]]; do
            unhealthy=$(docker ps --filter 'health=unhealthy' --format '{{.Names}}')
            starting=$(docker ps --filter 'health=starting' --format '{{.Names}}')
            if [[ -z "$unhealthy" && -z "$starting" ]]; then
               echo "✅ All containers are healthy"
               exit 0
            fi
            sleep 2
                ((timeout-=2))
              done
              echo "❌ Some containers are unhealthy or not ready!"
              docker ps
              exit 1
